/**
 * Curated word bank for composing "fragment + word" company name candidates.
 * Each entry: [word, one-phrase meaning used in generated rationale].
 * ~250 words across company-type suffixes, tech, abstract, and nature tiers.
 */
export const BUSINESS_WORDS: ReadonlyArray<readonly [string, string]> = [
  // ── Company-type suffixes ───────────────────────────────────────────────
  ['Labs', 'applied research and experimentation'],
  ['Lab', 'focused research and development'],
  ['Studio', 'creative production and craft'],
  ['Studios', 'creative production at scale'],
  ['Works', 'skilled craftsmanship and execution'],
  ['Group', 'multi-disciplinary enterprise'],
  ['Solutions', 'targeted problem-solving'],
  ['Systems', 'integrated technical architecture'],
  ['Technologies', 'pioneering technical innovation'],
  ['Technology', 'applied technical innovation'],
  ['Digital', 'digital-first operations'],
  ['Analytics', 'data-driven intelligence'],
  ['Ventures', 'bold entrepreneurial energy'],
  ['Capital', 'strategic investment and value creation'],
  ['Holdings', 'diversified portfolio stewardship'],
  ['Partners', 'trusted collaborative partnership'],
  ['Consulting', 'expert advisory services'],
  ['Advisory', 'strategic guidance and counsel'],
  ['Intelligence', 'deep analytical insight'],
  ['Innovations', 'breakthrough ideas and solutions'],
  ['Innovation', 'pioneering new approaches'],
  ['Networks', 'interconnected digital ecosystem'],
  ['Network', 'connected platform'],
  ['Services', 'professional service delivery'],
  ['Media', 'content creation and distribution'],
  ['Agency', 'creative and strategic execution'],
  ['Associates', 'collaborative professional association'],
  ['Dynamics', 'adaptive energetic movement'],
  ['Collective', 'unified shared-purpose community'],
  ['Collective', 'unified shared-purpose community'],
  ['Institute', 'knowledge and research authority'],
  ['Foundation', 'principled enduring mission'],
  ['Guild', 'skilled-craft community'],
  ['Atelier', 'artisanal bespoke creation'],
  ['Exchange', 'open-value marketplace'],
  ['Platform', 'enabling infrastructure layer'],
  ['Ecosystem', 'interconnected living system'],

  // ── Technology words ────────────────────────────────────────────────────
  ['Tech', 'technology-forward approach'],
  ['Code', 'software craftsmanship'],
  ['Data', 'data-driven methodology'],
  ['Cloud', 'cloud-native infrastructure'],
  ['Node', 'distributed network architecture'],
  ['Stack', 'full-stack technical capability'],
  ['Grid', 'interconnected computational grid'],
  ['Link', 'seamless connectivity'],
  ['Net', 'networked digital platform'],
  ['Web', 'web-first digital experience'],
  ['App', 'application-driven experience'],
  ['Byte', 'precision digital engineering'],
  ['Core', 'foundational technical layer'],
  ['Hub', 'central connectivity point'],
  ['Sync', 'seamless synchronisation'],
  ['Protocol', 'structured reliable foundation'],
  ['Layer', 'structured architectural depth'],
  ['Stack', 'full-capability technical platform'],
  ['Fabric', 'interwoven resilient architecture'],
  ['Matrix', 'structured multi-dimensional framework'],

  // ── Abstract / brand ────────────────────────────────────────────────────
  ['Edge', 'competitive advantage'],
  ['Peak', 'excellence at the summit'],
  ['Apex', 'pinnacle of achievement'],
  ['Nexus', 'point of convergence'],
  ['Flow', 'seamless continuous movement'],
  ['Path', 'guided strategic direction'],
  ['Pulse', 'responsive real-time energy'],
  ['Rise', 'upward momentum and growth'],
  ['Wave', 'transformative movement'],
  ['Signal', 'clear purposeful communication'],
  ['Bridge', 'connecting ideas and communities'],
  ['Gate', 'strategic gateway and access'],
  ['Forge', 'crafting strength through fire'],
  ['Sky', 'limitless aspiration'],
  ['Arc', 'sweeping progressive trajectory'],
  ['Axis', 'central point of rotation'],
  ['Beam', 'focused directional energy'],
  ['Crest', 'apex of achievement'],
  ['Dawn', 'new beginnings and opportunity'],
  ['Field', 'open space for growth'],
  ['Helm', 'leadership and navigation'],
  ['Hive', 'collaborative community intelligence'],
  ['Iris', 'clarity of vision'],
  ['Jade', 'precious enduring value'],
  ['Kite', 'elevated nimble flight'],
  ['Leap', 'bold decisive advancement'],
  ['Lens', 'focused perspicacity'],
  ['Loft', 'elevated creative vision'],
  ['Loop', 'continuous iterative improvement'],
  ['Mint', 'fresh precise innovation'],
  ['Mode', 'adaptive flexible approach'],
  ['Moon', 'reflective consistent presence'],
  ['Muse', 'creative inspiration and insight'],
  ['Nord', 'northern clarity and precision'],
  ['Opal', 'iridescent multi-faceted value'],
  ['Orb', 'complete unified presence'],
  ['Pact', 'committed trustworthy partnership'],
  ['Pier', 'strong stable foundation'],
  ['Reef', 'diverse thriving ecosystem'],
  ['Rock', 'solid dependable foundation'],
  ['Sage', 'wisdom and thoughtful guidance'],
  ['Salt', 'essential preserving value'],
  ['Seed', 'originating generative potential'],
  ['Silk', 'smooth refined excellence'],
  ['Span', 'bridging broad distance'],
  ['Spur', 'catalyst for accelerated growth'],
  ['Star', 'luminous guiding presence'],
  ['Stem', 'essential structural foundation'],
  ['Sun', 'radiant energising presence'],
  ['Tide', 'powerful rhythmic momentum'],
  ['Tone', 'distinctive resonant character'],
  ['Torch', 'illuminating forward progress'],
  ['Track', 'measured purposeful progress'],
  ['Trail', 'pioneering path-breaking journey'],
  ['Tree', 'deep-rooted sustainable growth'],
  ['Trek', 'determined purposeful journey'],
  ['True', 'authentic genuine commitment'],
  ['Turn', 'decisive directional change'],
  ['Vault', 'secure trusted repository'],
  ['Vein', 'rich flowing resource'],
  ['Wild', 'bold untamed innovation'],
  ['Wind', 'dynamic directional force'],
  ['Wing', 'enabling lift and flight'],
  ['Wise', 'informed thoughtful intelligence'],
  ['Yard', 'productive working space'],
  ['Zeal', 'passionate driven commitment'],
  ['Bold', 'courageous decisive action'],
  ['Bright', 'clear intelligent illumination'],
  ['Calm', 'steady composed confidence'],
  ['Clear', 'transparent purposeful clarity'],
  ['Crown', 'sovereign excellence and authority'],
  ['Deep', 'profound thoughtful depth'],
  ['Fair', 'equitable transparent exchange'],
  ['Fast', 'rapid responsive delivery'],
  ['Fine', 'precise refined quality'],
  ['Firm', 'steadfast reliable strength'],
  ['Good', 'wholesome beneficial purpose'],
  ['Grand', 'ambitious far-reaching vision'],
  ['Great', 'exceptional outstanding achievement'],
  ['High', 'elevated superior positioning'],
  ['Kind', 'caring human-centred approach'],
  ['Live', 'dynamic real-time engagement'],
  ['Long', 'enduring sustained commitment'],
  ['Loud', 'bold expressive voice'],
  ['Main', 'primary central focus'],
  ['Mark', 'distinctive recognisable identity'],
  ['More', 'expanding growing value'],
  ['Next', 'forward-looking progressive thinking'],
  ['Open', 'transparent accessible platform'],
  ['Pure', 'clean essential focus'],
  ['Real', 'authentic genuine value'],
  ['Safe', 'trusted secure environment'],
  ['Sure', 'reliable confident delivery'],
  ['True', 'authentic genuine commitment'],
  ['Wide', 'broad expansive reach'],

  // ── Geographic / nature ─────────────────────────────────────────────────
  ['River', 'continuous flowing momentum'],
  ['Harbor', 'safe strategic haven'],
  ['Grove', 'thriving interconnected community'],
  ['Ridge', 'elevated strategic vantage point'],
  ['Summit', 'pinnacle of achievement'],
  ['Vista', 'expansive forward-looking perspective'],
  ['Aurora', 'luminous transformative emergence'],
  ['Delta', 'fertile converging territory'],
  ['Bay', 'calm protected strategic position'],
  ['Cape', 'bold forward-facing position'],
  ['Cove', 'sheltered secure environment'],
  ['Glen', 'peaceful productive valley'],
  ['Hill', 'elevated clear perspective'],
  ['Lake', 'calm deep reflective resource'],
  ['Point', 'precise directional focus'],
  ['Range', 'broad comprehensive capability'],
  ['Shore', 'boundary-spanning frontier'],
  ['Vale', 'sheltered fruitful domain'],
  ['Knoll', 'elevated observant positioning'],
  ['Moor', 'expansive open potential'],

  // ── Mythological / abstract premium ────────────────────────────────────
  ['Atlas', 'foundational world-bearing strength'],
  ['Orion', 'celestial precision and guidance'],
  ['Nova', 'brilliant explosive emergence'],
  ['Zenith', 'apex of ascent and achievement'],
  ['Titan', 'immense powerful presence'],
  ['Prism', 'multi-spectrum creative refraction'],
  ['Spectrum', 'full-range comprehensive capability'],
  ['Catalyst', 'accelerating transformative change'],
  ['Quantum', 'precision at the smallest scale'],
  ['Vector', 'directed purposeful momentum'],
  ['Orbit', 'consistent reliable revolution'],
  ['Beacon', 'guiding illuminating direction'],
  ['Compass', 'reliable navigational certainty'],
  ['Frontier', 'pioneering boundary-expanding work'],
  ['Meridian', 'defining central alignment'],
  ['Axiom', 'self-evident foundational truth'],
  ['Astral', 'celestial aspiring vision'],
  ['Kinetic', 'dynamic energetic movement'],
  ['Echelon', 'elite ranked excellence'],
  ['Mirage', 'visionary imaginative possibility'],
  ['Azure', 'clear expansive blue-sky thinking'],
  ['Chrome', 'polished reflective precision'],
  ['Cyber', 'digital future-forward operation'],
  ['Quill', 'precise articulate expression'],
  ['Facet', 'multi-dimensional faceted value'],
  ['Cipher', 'encoded intelligent precision'],
  ['Helix', 'spiralling continuous advancement'],
  ['Nimbus', 'radiant cloud-like presence'],
  ['Ether', 'refined immaterial intelligence'],
  ['Comet', 'fast brilliant directed motion'],
  ['Epoch', 'era-defining transformative moment'],
  ['Glyph', 'symbolic distinctive mark'],
  ['Lyric', 'expressive resonant communication'],
  ['Myth', 'powerful narrative-driven identity'],
  ['Opus', 'masterwork defining achievement'],
  ['Psalm', 'principled enduring expression'],
  ['Rune', 'ancient wisdom encoded simply'],
  ['Tome', 'comprehensive knowledge repository'],
  ['Totem', 'iconic symbolic presence'],
  ['Trope', 'familiar reinvented freshly'],
  ['Verse', 'structured expressive communication'],
]
